### PR TITLE
LRQA-67242 Remove AssertLocation from Polls and Forms upgrade tests

### PR DESCRIPTION
**Pull request by brunofariasdeo**
https://issues.liferay.com/browse/LRQA-67242

@carolmariaabb @natocesarrego

### CODE REVIEW

**Comment by brunofariasdeo** [comment]
ci:test:sf

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:test:forms

**Comment by diogocordeiro** [comment]
ci:forward

**Pull request closed without merging**
