### PR TITLE
LRQA-68071 Fix Poshi tests

### PR DESCRIPTION
**Pull request by brunofariasdeo**
- LRQA-68071 - Fix FormsMultipleSelectionField#CanBeDeleted
- LRQA-68071 - Fix FormsSingleSelectionField#CanBeDeleted
- LRQA-68071 - Fix FormsTextField#CanBeValidatedUsingTheContainsOption
- LRQA-68071 - Fix FormsGridField#CanBeRequired
- LRQA-68071 - Fix FormsGridField#CanBeSubmitted
- LRQA-68071 - Fix FormsSelectFromListField#OptionsCanBeRearranged
- LRQA-68071 - sf

### CODE REVIEW

**Comment by brunofariasdeo** [comment]
ci:test:sf

**Comment by brunofariasdeo** [comment]
ci:test:forms

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:test:forms

**Comment by diogocordeiro** [comment]
ci:forward

**Pull request closed without merging**
